<?php
include_once("lib/GoogleAuthenticator.php");

if($_GET['type'] == "get"){

$authenticator = new PHPGangsta_GoogleAuthenticator();
 
$secret = $_GET['secret']; //This is used to generate QR code
$otp = $_GET['otp']; //Generated by Authenticator.
 
$tolerance = 0;
 
$checkResult = $authenticator->verifyCode($secret, $otp, $tolerance);    
 
if ($checkResult) 
{
    echo json_encode(array("status"=>200));
     
} else {
    echo json_encode(array("status"=>201));
}

}

if($_GET['type'] == "set"){

$authenticator = new PHPGangsta_GoogleAuthenticator();
$secret = $authenticator->createSecret(); //save this at server side
 
$website = 'فضاء التلاميذ'; //Your Website
$title= $_COOKIE['name']." - ".$_COOKIE['year']." ".$_COOKIE['div'];
$qrCodeUrl = $authenticator->getQRCodeGoogleUrl($title, $secret,$website);

echo json_encode(array("secret"=>$secret, "url"=>$qrCodeUrl));

}